# Generated by Django 4.1.2 on 2022-11-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donasi", "0010_alter_donasi_urlfoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donasi",
            name="foto",
            field=models.ImageField(upload_to="static/foto"),
        ),
        migrations.AlterField(
            model_name="donasi",
            name="urlFoto",
            field=models.TextField(default="/static/foto"),
        ),
    ]
